version: '3'

volumes:
  db-data:

networks:
  app:

services:
  database:
    image: postgres:12.5-alpine
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    ports:
      - "3306:3306"
    networks:
      - app
    volumes:
      - db-data:/var/lib/postgresql/data
      # - ./postgres/:/docker-entrypoint-initdb.d/

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "5000:5000"
      - "5003:5003"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app
    depends_on:
      - store-service

  store-service:
    image: php:7-fpm
    volumes:
      - ./store-service/:/var/www/app/
    networks:
      - app
    depends_on:
      - database

  warranty-service:
    image: php:7-fpm
    volumes:
      - ./warranty-service/:/var/www/app/
    networks:
      - app
    depends_on:
      - database